In [37]:
import torch
import numpy as np

# Tensores
- Estruturas de dados semelhantes a vetores ou matrizes
- Usadas no PyTorch tanto para representar *inputs* e *outputs*, como os pesos de uma rede neural
- Otimizados para rodar em gpu e para diferenciação automática

## Incialização de Tensores

In [38]:
# Inicialização a partir de listas
data = [[1, 2],[3, 4]]

x_data = torch.tensor(data)

x_data


tensor([[1, 2],
        [3, 4]])

In [39]:
# Inicialização a partir de arrays NumPy
np_array = np.array(data)

x_np = torch.from_numpy(np_array)

x_np

tensor([[1, 2],
        [3, 4]])

In [40]:
# Inicialização com valores constantes e aleatórios
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.8377, 0.2027, 0.6934],
        [0.9968, 0.5891, 0.4786]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [41]:
# Inicialização a partir de outros tensores:

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1251, 0.8065],
        [0.9553, 0.2382]]) 



# Propriedades de Tensores

- Forma
- Tipo
- Dispositivo

In [42]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Mudança de dispositivo

In [43]:
torch.cuda.is_available()

True

In [44]:
torch.cuda.device_count()

1

In [45]:
tensor = tensor.to("cuda") #cuda:index
tensor.device

device(type='cuda', index=0)

In [46]:
tensor = tensor.to("cpu")
tensor.device

device(type='cpu')

In [47]:
# Uma solução mais geral
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
tensor.device

device(type='cuda', index=0)

# Operações com Tensores

In [48]:
# Fatiamento e Indexação:

tensor = torch.tensor(data)
print(f"Tensor:\n {tensor}")

print(f"(A) First row: {tensor[0]}")
print(f"(B) First column: {tensor[:, 0]}")
print(f"(C) Last column: {tensor[..., -1]}")

tensor[:,1] = 0
print(f"(D) Tensor modificado:\n {tensor}")

Tensor:
 tensor([[1, 2],
        [3, 4]])
(A) First row: tensor([1, 2])
(B) First column: tensor([1, 3])
(C) Last column: tensor([2, 4])
(D) Tensor modificado:
 tensor([[1, 0],
        [3, 0]])


In [49]:
# Concatenação de Tensores:
tensor = torch.tensor(data)

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])
tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])


## Operações Aritméticas

In [50]:
#Transposição
print(f"(A) Tensor transposto:\n {tensor.T}")
# Ou alternativamente:
print(f"(B) Tensor transposto:\n {tensor.transpose(0,1)}") # Essa solução é geral, e permite transpor quaisquer duas dimensões num tensor n-dimensional:

(A) Tensor transposto:
 tensor([[1, 3],
        [2, 4]])
(B) Tensor transposto:
 tensor([[1, 3],
        [2, 4]])


In [51]:
#Produto Tensorial
y = tensor.T @ tensor
y

tensor([[10, 14],
        [14, 20]])

In [52]:
# Produto elemento a elemento
y = tensor * tensor
y

tensor([[ 1,  4],
        [ 9, 16]])

In [53]:
#Agregação
y = torch.sum(tensor)
print(f"Soma: {y}")

print(f"Média: {torch.mean(tensor.float())}")

print(f"Produto: {torch.prod(tensor)}")


Soma: 10
Média: 2.5
Produto: 24


In [54]:
print(y)
y.item()

tensor(10)


10

## Operações *in place*

Várias operações tem variações *in place*, que alteram o próprio tensor ao invés de criar um novo. Isso economiza memória, mas leva `perda do histŕoico de operações que seria usado para a diferenciação automática.

In [55]:
# Normal
tensor = torch.tensor(data)
print(tensor.add(5))
print(tensor)

print("---")

#In place:
print(tensor.add_(5))
print(tensor)

tensor([[6, 7],
        [8, 9]])
tensor([[1, 2],
        [3, 4]])
---
tensor([[6, 7],
        [8, 9]])
tensor([[6, 7],
        [8, 9]])
